### PR TITLE
Fix build on some devices

### PR DESCRIPTION
**Pull request by PikaPikaFreed**
Fullfill some missing declarations that cause error

### CODE REVIEW

**Comment by Astridxx** [comment]
Encryption working after this fix?

**Comment by PikaPikaFreed** [comment]
For me yes

**Comment by NurKeinNeid** [comment]
Interesting. Thank you. I'll check that out.

**Comment by PikaPikaFreed** [comment]
It works on my lavender, it fixed encryption thingy

**Pull request merged**
